import { useEffect, useState } from "react";
import { Bell, Download, FileUp, Play, Plus, RefreshCw, Save } from "lucide-react";
import { apiDownload, apiGet, apiPost, apiPut, apiUpload } from "../lib/api.js";

const tomorrow=()=>new Date(Date.now()+86400000).toISOString().slice(0,10);

export function EveningPreparation({token}){
  const [cases,setCases]=useState([]),[logs,setLogs]=useState([]),[date,setDate]=useState(tomorrow()),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const load=async()=>{try{const [c,l]=await Promise.all([apiGet("/cases",token),apiGet(`/operations/evening-logs?date=${date}`,token)]);setCases(c.cases||[]);setLogs(l.logs||[]);}catch(e){setError(e.message);}};
  useEffect(()=>{load();},[date]);
  const generate=async()=>{try{const r=await apiPost("/operations/evening-logs/generate",{date},token);setNotice(r.message);await load();}catch(e){setError(e.message);}};
  const save=async(log)=>{try{await apiPost("/operations/evening-logs",log,token);setNotice(`Saved ${log.case_no}`);await load();}catch(e){setError(e.message);}};
  const toggles=["io_contacted","sho_contacted","acp_contacted","dcp_contacted","spp_briefed","case_file_traced","cd_updated","para_wise_remarks_ready","personal_appearance_required","briefing_note_prepared"];
  return <Module title="Evening Preparation Log" subtitle="Complete the pre-hearing checklist for tomorrow's matters." error={error} notice={notice} action={<><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button onClick={generate}><Plus size={16}/>Generate</button></>}>
    <div className="tracker-list">{logs.map(log=><div className="tracker-row" key={log.id}><div><strong>{log.case_no}</strong><span>{log.police_station_name}</span></div><div className="check-grid">{toggles.map(f=><label className="check compact-check" key={f}><input type="checkbox" checked={!!log[f]} onChange={e=>setLogs(x=>x.map(v=>v.id===log.id?{...v,[f]:e.target.checked}:v))}/>{label(f)}</label>)}</div><textarea placeholder="Remarks" value={log.remarks||""} onChange={e=>setLogs(x=>x.map(v=>v.id===log.id?{...v,remarks:e.target.value}:v))}/><button className="secondary" onClick={()=>save(log)}><Save size={16}/>Save</button></div>)}</div>
    {!logs.length&&<div className="panel"><p className="muted">No logs yet. Set a date and generate from matching Master Register hearing dates.</p></div>}
  </Module>;
}

export function OfficerPerformance({token}){
  const blank={officer_name:"",police_station_id:"",no_of_hc_cases:0,delayed_submissions:0,adverse_remarks:0,appreciations:0,avg_compliance_time_days:0,risk_category:"Low",remarks:"",report_month:new Date().toISOString().slice(0,7)+"-01"};
  const [masters,setMasters]=useState({policeStations:[]}),[items,setItems]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const load=async()=>{try{const [m,p]=await Promise.all([apiGet("/masters",token),apiGet("/operations/performance",token)]);setMasters(m);setItems(p.officers||[]);}catch(e){setError(e.message);}};useEffect(()=>{load();},[]);
  const save=async e=>{e.preventDefault();try{editing?await apiPut(`/operations/performance/${editing}`,form,token):await apiPost("/operations/performance",form,token);setNotice("Performance record saved");setForm(blank);setEditing(null);await load();}catch(x){setError(x.message);}};
  return <Module title="Officer Legal Performance" subtitle="Track delays, remarks, appreciations, and monthly officer risk." error={error} notice={notice}><form className="case-form" onSubmit={save}><Field label="Officer Name" value={form.officer_name} set={v=>setForm({...form,officer_name:v})}/><label>Police Station<select value={form.police_station_id} onChange={e=>setForm({...form,police_station_id:e.target.value})}><option value="">Select</option>{masters.policeStations.map(p=><option value={p.police_station_id} key={p.police_station_id}>{p.station_name}</option>)}</select></label>{["no_of_hc_cases","delayed_submissions","adverse_remarks","appreciations","avg_compliance_time_days"].map(f=><Field key={f} label={label(f)} type="number" value={form[f]} set={v=>setForm({...form,[f]:v})}/>)}<label>Risk<select value={form.risk_category} onChange={e=>setForm({...form,risk_category:e.target.value})}>{["Low","Medium","High"].map(v=><option key={v}>{v}</option>)}</select></label><label className="wide">Remarks<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label><button className="primary"><Save size={16}/>Save</button></form><SimpleTable headers={["Officer","PS","Cases","Delayed","Adverse","Appreciations","Avg Days","Risk"]} rows={items.map(x=>[x.officer_name,x.police_station_name,x.no_of_hc_cases,x.delayed_submissions,x.adverse_remarks,x.appreciations,x.avg_compliance_time_days,x.risk_category])}/></Module>;
}

export function AnalyticsReports({token}){
  const [data,setData]=useState(null),[error,setError]=useState("");const load=()=>apiGet("/operations/analytics",token).then(setData).catch(e=>setError(e.message));useEffect(load,[]);
  return <Module title="Analytics & Reports" subtitle="Litigation distribution, monthly trends, and exportable case reports." error={error} action={<><button onClick={()=>apiDownload("/operations/analytics/export",token,"hcmc-analytics-report.xlsx")}><Download size={16}/>Excel</button><button className="secondary" onClick={()=>apiDownload("/operations/analytics/export-pdf",token,"hcmc-analytics-report.pdf")}><Download size={16}/>PDF</button></>}>
    {data&&<><div className="stat-grid"><Kpi label="Total Cases" value={data.totals.total}/><Kpi label="Active" value={data.totals.active}/><Kpi label="Disposed" value={data.totals.disposed}/><Kpi label="Disposed Bail" value={data.outcomes.bail_disposed}/></div><div className="report-grid"><SimpleTable title="Cases by Type" headers={["Type","Cases"]} rows={data.byType.map(x=>[x.label,x.value])}/><SimpleTable title="Cases by Police Station" headers={["Police Station","Cases"]} rows={data.byStation.map(x=>[x.label,x.value])}/><SimpleTable title="Monthly Filing Trend" headers={["Month","Cases"]} rows={data.monthlyTrend.map(x=>[x.label,x.value])}/></div></>}
  </Module>;
}

export function DocumentRepository({token,role}){
  const [docs,setDocs]=useState([]),[file,setFile]=useState(null),[form,setForm]=useState({title:"",category:"Judgment",case_no:"",document_date:"",tags:""}),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const load=()=>apiGet("/operations/documents",token).then(x=>setDocs(x.documents||[])).catch(e=>setError(e.message));useEffect(load,[]);
  const upload=async e=>{e.preventDefault();try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v));fd.append("file",file);await apiUpload("/operations/documents",fd,token);setNotice("Document uploaded");e.target.reset();await load();}catch(x){setError(x.message);}};
  return <Module title="Document Repository" subtitle="Store and retrieve judgments, orders, and landmark rulings." error={error} notice={notice}>{role==="PI"&&<form className="upload-panel" onSubmit={upload}><Field label="Title" value={form.title} set={v=>setForm({...form,title:v})}/><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["Judgment","Bail Order","Quashing Order","Contempt Order","Policy","Other"].map(v=><option key={v}>{v}</option>)}</select></label><input type="file" required onChange={e=>setFile(e.target.files?.[0])}/><button><FileUp size={16}/>Upload</button></form>}<SimpleTable headers={["Title","Category","Case","Date","Uploaded By","File"]} rows={docs.map(d=>[d.title,d.category,d.case_no||"",formatDate(d.document_date),d.uploaded_by_name,<button className="secondary" onClick={()=>apiDownload(`/operations/documents/${d.id}/download`,token,d.original_name)}><Download size={15}/></button>])}/></Module>;
}

export function MastersSettings({token}){
  const [data,setData]=useState({caseTypes:[],caseStages:[],users:[],notificationSettings:[]}),[type,setType]=useState({code:"",name:""}),[stage,setStage]=useState({name:"",description:""}),[user,setUser]=useState({name:"",email:"",password:"Hcmc@123",role:"IO",mobile_no:""}),[notify,setNotify]=useState({user_id:"",phone_number:"",whatsapp_number:"",sms_enabled:false,whatsapp_enabled:false}),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const load=()=>apiGet("/operations/settings",token).then(setData).catch(e=>setError(e.message));useEffect(load,[]);
  const save=async(path,body)=>{try{path.endsWith("/active")?await apiPut(path,body,token):await apiPost(path,body,token);setNotice("Setting saved");await load();}catch(e){setError(e.message);}};
  return <Module title="Masters & Settings" subtitle="Manage case types, stages, users, and notification contacts." error={error} notice={notice}><div className="report-grid"><form className="panel" onSubmit={e=>{e.preventDefault();save("/operations/settings/case-types",type)}}><h2>Case Type</h2><Field label="Code" value={type.code} set={v=>setType({...type,code:v})}/><Field label="Name" value={type.name} set={v=>setType({...type,name:v})}/><button><Plus size={16}/>Save</button></form><form className="panel" onSubmit={e=>{e.preventDefault();save("/operations/settings/case-stages",stage)}}><h2>Case Stage</h2><Field label="Name" value={stage.name} set={v=>setStage({...stage,name:v})}/><Field label="Description" value={stage.description} set={v=>setStage({...stage,description:v})}/><button><Plus size={16}/>Save</button></form><form className="panel" onSubmit={e=>{e.preventDefault();save("/operations/settings/users",user)}}><h2>Create User</h2><Field label="Name" value={user.name} set={v=>setUser({...user,name:v})}/><Field label="Email" value={user.email} set={v=>setUser({...user,email:v})}/><Field label="Password" value={user.password} set={v=>setUser({...user,password:v})}/><label>Role<select value={user.role} onChange={e=>setUser({...user,role:e.target.value})}>{["JCP","DCP","ACP","PI","IO","HCMC_STAFF","SPP"].map(v=><option key={v}>{v}</option>)}</select></label><button><Plus size={16}/>Create</button></form><form className="panel" onSubmit={e=>{e.preventDefault();save("/operations/settings/notifications",notify)}}><h2>Notification Contact</h2><label>User<select value={notify.user_id} onChange={e=>setNotify({...notify,user_id:e.target.value})}><option value="">Select</option>{data.users.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><Field label="Phone" value={notify.phone_number} set={v=>setNotify({...notify,phone_number:v})}/><Field label="WhatsApp" value={notify.whatsapp_number} set={v=>setNotify({...notify,whatsapp_number:v})}/><label className="check compact-check"><input type="checkbox" checked={notify.sms_enabled} onChange={e=>setNotify({...notify,sms_enabled:e.target.checked})}/>SMS enabled</label><label className="check compact-check"><input type="checkbox" checked={notify.whatsapp_enabled} onChange={e=>setNotify({...notify,whatsapp_enabled:e.target.checked})}/>WhatsApp enabled</label><button><Save size={16}/>Save</button></form></div><SimpleTable title="Users" headers={["Name","Email","Role","Mobile","Active","Action"]} rows={data.users.map(u=>[u.name,u.email,u.role,u.mobile_no,u.active?"Yes":"No",<button className="secondary" onClick={()=>save(`/operations/settings/users/${u.id}/active`,{active:!u.active})}>{u.active?"Deactivate":"Activate"}</button>])}/></Module>;
}

export function AutomationCenter({token}){
  const [data,setData]=useState({configured:{},pollRuns:[],notificationLogs:[]}),[date,setDate]=useState(tomorrow()),[notice,setNotice]=useState(""),[error,setError]=useState("");const load=()=>apiGet("/automation/status",token).then(setData).catch(e=>setError(e.message));useEffect(load,[]);
  const run=async(path,body={})=>{try{const r=await apiPost(path,body,token);setNotice(JSON.stringify(r));await load();}catch(e){setError(e.message);}};
  return <Module title="Notifications & Automation" subtitle="Monitor scheduled reminders, delivery logs, and High Court cause-list polling." error={error} notice={notice} action={<button onClick={load}><RefreshCw size={16}/>Refresh</button>}><div className="stat-grid"><Kpi label="Cause URL Configured" value={data.configured.causeListUrl?"Yes":"No"}/><Kpi label={`${data.configured.notificationProvider||"Preview"} Provider`} value={data.configured.notificationConfigured?"Ready":"Needs setup"}/></div><div className="automation-actions"><button onClick={()=>run("/automation/run-reminders")}><Bell size={16}/>Run Reminders</button><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button onClick={()=>run("/automation/poll-cause-list",{listingDate:date})}><Play size={16}/>Poll Cause List</button></div><SimpleTable title="Recent Polls" headers={["Time","Status","Found","Created","Details"]} rows={data.pollRuns.map(x=>[formatDateTime(x.polled_at),x.status,x.cases_found,x.entries_created,x.details])}/><SimpleTable title="Notification Logs" headers={["Time","Event","Case","Channel","Status","Recipients"]} rows={data.notificationLogs.map(x=>[formatDateTime(x.created_at),x.event_type,x.case_no,x.channel,x.status,x.recipients])}/></Module>;
}

function Module({title,subtitle,error,notice,action,children}){return <section><div className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions">{action}</div></div>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}{children}</section>}
function Field({label:caption,value,set,type="text"}){return <label>{caption}<input type={type} value={value??""} onChange={e=>set(e.target.value)} required/></label>}
function Kpi({label:caption,value}){return <article className="stat-card"><span>{caption}</span><strong>{value??0}</strong></article>}
function SimpleTable({title,headers,rows=[]}){return <div className="panel table-wrap">{title&&<h2>{title}</h2>}<table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={headers.length} className="empty">No records</td></tr>}</tbody></table></div>}
function label(v){return v.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function formatDate(v){return v?new Date(v).toLocaleDateString("en-IN"):""}
function formatDateTime(v){return v?new Date(v).toLocaleString("en-IN"):""}
